### ISSUE TITLE
Self signed certificate 

### ISSUE THREAD

**Issue by Grga23** [mowlc/real-estate-scraper#2]
I get the following error once I run the script.

"Error sending mail: Error: self signed certificate in certificate chain"

Any idea how to resolve this issue? 
Thanks!

**Comment by mowlc** [comment]
Hi!
Have you tried changing Google less secure apps settings?
Anyways, I'm preparing new version with updated scraper for both pages and Google OAuth2 authentication with instruction on how to do it. I will push it in a week or two.
Regards

**Comment by Grga23** [comment]
Hi!

Yea i turned that on.
No prob :) will wait for the newer version then.
Thanks for getting back!

**Comment by mowlc** [comment]
Hi!
just pushed the new version. Enjoy!
