### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by davision** [mowlc/real-estate-scraper#3]
I keep getting this error:

```
real-estate-scraper/scraper.js:68
	price: bAds[i].children[7].children[1].children[0].children[0].data
                                                                    ^
TypeError: Cannot read property '0' of undefined
```

Do you have a clue, what could be the problem? Tried to remove Bolha scraping, but for Nepremicnice happens the same but after a couple of iterations.

**Comment by mowlc** [comment]
I think that both providers hanged their sites a bit. I'm preparing new version, that should be pushed in next week or two.

**Comment by davision** [comment]
I thought that might be a problem too. Will try to play with it myself in a meantime. Is it possible to add multiple search URLs for a specific website?

**Comment by mowlc** [comment]
Hi!
I just pushed the new version. It also features adding more than one search URL per website.
